--Quote--
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Þegar ég vaknaði um morguninn er þú komst inn til mín. Hörund þitt eins og silki andlitið eins og postulín.' ,0 ,'Bubbi Mortens: Stál og Hnífur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Við bryggjuna bátur vaggar hljótt, í nótt mun ég deyja. Mig dreymdi dauðinn segði komdu fljótt það er svo margt sem ég ætla þér að segja.' ,0 ,'Bubbi Mortens: Stál og Hnífur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Ef ég drukkna drukkna í nótt, ef þeir mig finna. Þú getur komið og mig sótt þá vil ég á það minna.' ,0 ,'Bubbi Mortens: Stál og Hnífur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Stál og hnífur er merki mitt merki farandverkamanna. Þitt var mitt og mitt var þitt meðan ég bjó á meðal manna.' ,0 ,'Bubbi Mortens: Stál og Hnífur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Uppi í risinu sérðu lítið ljós, Heit hjörtu, fölnuð rós, Matarleifar, bogin skeið, Undan oddinum samviskan sveið.' ,0 ,'Bubbi Mortens: Rómeó og Júlía',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Þau trúðu á draumamyrkrið svalt, Draumarnir tilbáðu þau, Fingurnir gældu við stálið kalt, Lífsvökvann dælan saug.' ,0 ,'Bubbi Mortens: Rómeó og Júlía',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Draumarnir langir runnu í eitt, Dofin þau fylgdu með, Sprautan varð lífið, með henni gátu breytt, Því sem átti eftir að ske.' ,0 ,'Bubbi Mortens: Rómeó og Júlía',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Mávahvítt ský dormar dofið Inn í draum vindsins er það ofið Hreyfist vart úr stað.' ,0 ,'Bubbi Mortens: Fallegi dagur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Konurnar blómstra brosandi sælar Sumarkjólar háir hælar Kvöldið vill komast að ' ,0 ,'Bubbi Mortens: Fallegi dagur',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
Insert into quotes(text,language,origin,accepted,daily,created_at,updated_at) Values('Brosið og bláu augun dáleiða um leið, eitt augnaráð og ég er háð þér, en rólegur kúreki, koddu niður af háa hestinum, hvernig væri að líta inn á við, þú ert ekki einn í heiminum' ,0 ,'BRÍET: Rólegur Kúreki',true,false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
